Dev
VictoriaZmushko/my_news_site_project pull request #1
Opened 2024-03-28 17:31 UTC by VictoriaZmushko

2024-03-28 17:46 UTC, udevgeektutor requested changes

2024-03-28 17:46 UTC, udevgeektutor commented on mywebsite/db.sqlite3
поиграйся с gitignore. База данных всёже улетела на гитхаб.

2024-03-28 17:46 UTC, udevgeektutor commented on mywebsite/mywebsite/__pycache__/__init__.cpython-311.pyc
Дополни gitignore файл, никаких пайкешей на гитхаб не должно улетать.

2024-03-28 17:46 UTC, udevgeektutor commented on mywebsite/mywebsite/__pycache__/settings.cpython-311.pyc
Дополни gitignore файл, никаких пайкешей на гитхаб не должно улетать.

2024-03-28 17:46 UTC, udevgeektutor commented on mywebsite/mywebsite/__pycache__/urls.cpython-311.pyc
Дополни gitignore файл, никаких пайкешей на гитхаб не должно улетать.

2024-03-28 17:46 UTC, udevgeektutor commented on mywebsite/mywebsite/__pycache__/wsgi.cpython-311.pyc
Дополни gitignore файл, никаких пайкешей на гитхаб не должно улетать.

2024-03-28 17:46 UTC, udevgeektutor commented on mywebsite/news/__pycache__/__init__.cpython-311.pyc
Аналогично. Редактируй гитигнор, этих файлов тут не должно быть.

2024-03-28 17:46 UTC, udevgeektutor commented on mywebsite/news/admin.py
> +
Можно удалить если не используешь.
```suggestion
```

2024-03-28 17:46 UTC, udevgeektutor commented on mywebsite/news/admin.py
> +from .models import Article
```suggestion
from django.contrib import admin

from .models import Article
```

2024-03-28 17:46 UTC, udevgeektutor commented on mywebsite/news/migrations/__pycache__/0001_initial.cpython-311.pyc
Аналогично. Редактируй гитигнор, этих файлов тут не должно быть.

2024-03-28 17:46 UTC, udevgeektutor commented on mywebsite/news/urls.py
> +    # post
```suggestion
```

2024-03-28 17:46 UTC, udevgeektutor commented on mywebsite/news/views.py
> +from .models import Article
```suggestion
from django.shortcuts import get_object_or_404

from .models import Article
```

2024-03-28 18:52 UTC, VictoriaZmushko commented on mywebsite/db.sqlite3
Готово

2024-03-28 18:52 UTC, VictoriaZmushko commented on mywebsite/mywebsite/__pycache__/wsgi.cpython-311.pyc
Все убрала.

2024-03-28 19:07 UTC, VictoriaZmushko commented on mywebsite/news/migrations/__pycache__/0001_initial.cpython-311.pyc
Убрала.

2024-03-28 19:08 UTC, VictoriaZmushko commented on mywebsite/news/__pycache__/__init__.cpython-311.pyc
+

2024-03-28 19:20 UTC, VictoriaZmushko commented on mywebsite/mywebsite/__pycache__/__init__.cpython-311.pyc
Сделано

2024-03-28 19:20 UTC, VictoriaZmushko commented on mywebsite/mywebsite/__pycache__/settings.cpython-311.pyc
Сделано

2024-03-28 19:20 UTC, VictoriaZmushko commented on mywebsite/mywebsite/__pycache__/urls.cpython-311.pyc
Есть

2024-03-28 19:20 UTC, VictoriaZmushko commented on mywebsite/news/__pycache__/__init__.cpython-311.pyc
Исправлено

2024-03-28 19:28 UTC, VictoriaZmushko commented on mywebsite/news/admin.py
> +
Удалено.

2024-03-28 19:28 UTC, VictoriaZmushko commented on mywebsite/news/urls.py
> +    # post
Удалено.

2024-03-28 19:34 UTC, VictoriaZmushko commented on mywebsite/news/views.py
> +from .models import Article
Все сделано.

2024-03-28 19:34 UTC, VictoriaZmushko commented on mywebsite/news/admin.py
> +from .models import Article
Готово

2024-04-02 15:47 UTC, udevgeektutor approved these changes

2024-04-02 15:57 UTC, merged